version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: oms_postgres_db
 
    ports:
      - "5432:5432"
    volumes:
      - /opt/oms/infra/export/postgresql:/var/lib/postgresql/data
    networks:
      - oms_network
    restart: always


networks:
  oms_network:
    