version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: oms-redis
    ports:
      - "6379:6379"
    volumes:
      - /opt/oms/infra/export/redis:/data
    networks:
      - oms_network
    restart: always


networks:
  oms_network: